# Site Settings
title: "Hyunseung Lee"
name: "Hyunseung Lee"
description: "M.A. Economics @ Seoul National University"
url: "https://hyunseung-data.github.io"
baseurl: ""

# Theme - Academic Pages
remote_theme: "academicpages/academicpages.github.io"

locale: "en-US"
markdown: kramdown

# Site Author
author:
  name: "Hyunseung Lee"
  avatar: "/assets/img/profile.jpeg"
  bio: "M.A. Economics @ SNU<br>Aspiring Data Scientist"
  location: "Seoul, South Korea"
  email: "thomas96124@gmail.com"
  github: "hyunseung-data"

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Include
include: ["_pages"]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme
